name: Create Draft Release

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  create_release:
    if: github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set VERSION
        run: echo "VERSION=1.16.0" >> $GITHUB_ENV

      - name: Create Draft Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          release_name: 'Draft Release v${{ env.VERSION }}'
          draft: true
          body: |
            This is a draft release for version v${{ env.VERSION }}.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}